In [37]:
%pip uninstall gensim -y

Found existing installation: gensim 4.3.3
Uninstalling gensim-4.3.3:
  Successfully uninstalled gensim-4.3.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [43]:
%pip install gensim==3.8.1

Collecting gensim==3.8.1
  Using cached gensim-3.8.1-cp312-cp312-linux_x86_64.whl
Requirement already satisfied: numpy>=1.11.3 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.26.4)
Requirement already satisfied: scipy>=0.18.1 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.13.1)
Requirement already satisfied: six>=1.5.0 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.17.0)
Requirement already satisfied: smart_open>=1.8.1 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (7.3.0.post1)
Requirement already satisfied: wrapt in /root/miniforge3/lib/python3.12/site-packages (from smart_open>=1.8.1->gensim==3.8.1) (1.17.2)
Installing collected packages: gensim
Successfully installed gensim-3.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec 
import random
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline
import warnings;
warnings.filterwarnings('ignore')

ImportError: cannot import name 'triu' from 'scipy.linalg.special_matrices' (/root/miniforge3/lib/python3.12/site-packages/scipy/linalg/special_matrices.py)

In [ ]:
df_movies = pd.read_csv('movies.csv')
df_ratings = pd.read_csv('ratings.csv')

In [ ]:
df_movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10324,146684,Cosmic Scrat-tastrophe (2015),Animation|Children|Comedy
10325,146878,Le Grand Restaurant (1966),Comedy
10326,148238,A Very Murray Christmas (2015),Comedy
10327,148626,The Big Short (2015),Drama
10328,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed)

In [ ]:
df = pd.merge(df_movies,df_ratings)

In [ ]:
df.tail(100)

,movieId,title,genres,userId,rating,timestamp
105239,135460,Pablo (2012),(no genres listed),475,3.5,1441965768
105240,135504,Little Boy (2015),Comedy|Drama|War,504,4.0,1447973704
105241,135532,The Last Witch Hunter (2015),Action|Adventure|Fantasy,622,3.0,1447456580
105242,135534,Krampus (2015),Comedy|Fantasy|Horror,622,3.0,1450207387
105243,135861,Ted 2 (2015),Comedy,106,4.0,1440860990
...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas (2015),Comedy,475,3.0,1451213043
105335,148626,The Big Short (2015),Drama,458,4.0,1452014749
105336,148626,The Big Short (2015),Drama,576,4.5,1451687664
105337,148626,The Big Short (2015),Drama,668,4.5,1451148148
105338,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed),475,4.0,1451223429

In [ ]:
df.dropna(inplace=True)

In [ ]:
df['movieId']= df['movieId'].astype(str)
users = df["userId"].unique().tolist()
len(users)

668

In [ ]:
random.shuffle(users)
# extract 90% of user ID's
users_train = [users[i] for i in range(round(0.9*len(users)))]
# split data into train and validation set
train_df = df[df['userId'].isin(users_train)]
validation_df = df[~df['userId'].isin(users_train)]

In [ ]:
#list to capture watch history of the users
watch_train = []
# populate the list with the movie ID
for i in tqdm(users_train):
    temp = train_df[train_df["userId"] == i]["movieId"].tolist()
    watch_train.append(temp)

  0%|          | 0/601 [00:00<?, ?it/s]

100%|██████████| 601/601 [00:00<00:00, 2502.91it/s]

In [ ]:
watch_train

[['1',
  '10',
  '11',
  '17',
  '19',
  '34',
  '39',
  '47',
  '50',
  '95',
  '110',
  '111',
  '150',
  '151',
  '153',
  '160',
  '161',
  '165',
  '172',
  '173',
  '185',
  '186',
  '196',
  '204',
  '208',
  '225',
  '231',
  '236',
  '253',
  '266',
  '292',
  '293',
  '296',
  '300',
  '315',
  '316',
  '317',
  '318',
  '329',
  '339',
  '344',
  '349',
  '356',
  '364',
  '367',
  '377',
  '380',
  '410',
  '420',
  '432',
  '434',
  '454',
  '457',
  '474',
  '480',
  '508',
  '527',
  '529',
  '553',
  '588',
  '590',
  '592',
  '593',
  '594',
  '595',
  '596',
  '733',
  '748'],
 ['14',
  '107',
  '135',
  '306',
  '562',
  '637',
  '743',
  '1296',
  '1299',
  '2108',
  '2359',
  '2478',
  '2872',
  '3105',
  '3247',
  '3252',
  '3362',
  '3698',
  '4270',
  '79132'],
 ['261',
  '313',
  '597',
  '837',
  '900',
  '902',
  '911',
  '917',
  '928',
  '940',
  '946',
  '965',
  '1082',
  '1907',
  '1959',
  '2202',
  '2203',
  '2248',
  '2302',
  '2572',
  '2763',
  '3072',
  '4011',
  '4359',
  '4993',
  '5418',
  '6378',
  '6539',
  '7153',
  '7293',
  '7458',
  '7669',
  '26528',
  '27368',
  '31694',
  '33679',
  '38038',
  '41566',
  '44193',
  '44665',
  '45722',
  '46967',
  '50796',
  '51471',
  '51662',
  '53125',
  '53956',
  '54259',
  '54372',
  '60397',
  '62293',
  '63082',
  '64285',
  '64957',
  '67255',
  '68269',
  '68554',
  '69844',
  '73017',
  '74545',
  '79293',
  '80549',
  '81834',
  '83302',
  '88125',
  '88131',
  '90403'],
 ['480',
  '1201',
  '1230',
  '1617',
  '1732',
  '1961',
  '3176',
  '3681',
  '3814',
  '3863',
  '3879',
  '3882',
  '3898',
  '3916',
  '3943',
  '3967',
  '3969',
  '3973',
  '3977',
  '3978',
  '3981'],
 ['2',
  '3',
  '30',
  '32',
  '46',
  '60',
  '104',
  '111',
  '141',
  '180',
  '208',
  '231',
  '232',
  '260',
  '296',
  '326',
  '329',
  '355',
  '356',
  '357',
  '365',
  '370',
  '441',
  '446',
  '500',
  '508',
  '509',
  '538',
  '539',
  '552',
  '587',
  '589',
  '590',
  '592',
  '593',
  '608',
  '714',
  '778',
  '800',
  '851',
  '858',
  '870',
  '891',
  '903',
  '904',
  '912',
  '913',
  '919',
  '920',
  '924',
  '944',
  '952',
  '953',
  '968',
  '969',
  '991',
  '1007',
  '1010',
  '1013',
  '1019',
  '1036',
  '1037',
  '1060',
  '1073',
  '1081',
  '1084',
  '1085',
  '1086',
  '1089',
  '1090',
  '1091',
  '1097',
  '1101',
  '1103',
  '1104',
  '1125',
  '1127',
  '1129',
  '1136',
  '1183',
  '1193',
  '1194',
  '1196',
  '1198',
  '1201',
  '1204',
  '1206',
  '1208',
  '1210',
  '1213',
  '1214',
  '1219',
  '1220',
  '1221',
  '1222',
  '1225',
  '1233',
  '1234',
  '1240',
  '1246',
  '1247',
  '1249',
  '1250',
  '1252',
  '1253',
  '1256',
  '1258',
  '1263',
  '1265',
  '1270',
  '1272',
  '1278',
  '1280',
  '1287',
  '1288',
  '1291',
  '1293',
  '1302',
  '1304',
  '1307',
  '1317',
  '1321',
  '1328',
  '1333',
  '1340',
  '1343',
  '1344',
  '1347',
  '1350',
  '1358',
  '1370',
  '1371',
  '1373',
  '1374',
  '1375',
  '1376',
  '1380',
  '1387',
  '1388',
  '1391',
  '1393',
  '1407',
  '1431',
  '1439',
  '1449',
  '1480',
  '1485',
  '1517',
  '1580',
  '1610',
  '1617',
  '1619',
  '1641',
  '1682',
  '1694',
  '1704',
  '1717',
  '1729',
  '1730',
  '1732',
  '1747',
  '1748',
  '1753',
  '1772',
  '1831',
  '1909',
  '1921',
  '1947',
  '1952',
  '1954',
  '1955',
  '1958',
  '1961',
  '1962',
  '1968',
  '1974',
  '1982',
  '1987',
  '1994',
  '1997',
  '2003',
  '2005',
  '2009',
  '2013',
  '2015',
  '2021',
  '2034',
  '2060',
  '2067',
  '2068',
  '2078',
  '2087',
  '2115',
  '2117',
  '2118',
  '2121',
  '2122',
  '2124',
  '2132',
  '2136',
  '2145',
  '2150',
  '2160',
  '2169',
  '2174',
  '2184',
  '2243',
  '2284',
  '2291',
  '2302',
  '2306',
  '2324',
  '2336',
  '2352',
  '2375',
  '2378',
  '2391',
  '2396',
  '2398',
  '2401',
  '2402',
  '2406',
  '2420',
  '2423',
  '2454',
  '2455',
  '2456',
  '2459',
  '2468',
  '2470',
  '2476',
  '2478',
  '2513',
  '2517',
  '2518',
  '2524',
  '2527',
  '2529',
  '2530',
  '2533',
  '2551',
  '2571',
  '2582',
  '2621',
  '2648',
  '2657',
  '2664',
  '2676',
  '2677',
  '2683',
  '2686',
  '2699',
  '2716',
  '2746',
  '2762',
  '2782',
  '2789',
  '2792',
  '2797',
  '2819',
  '2857',
  '2863',
  '2870',
  '2871',
  '2916',
  '2918',
  '2942',
  '2946',
  '2947',
  '2949',
  '2951',
  '2976',
  '2985',
  '2991',
  '2997',
  '3015',
  '3024',
  '3032',
  '3033',
  '3035',
  '3039',
  '3060',
  '3066',
  '3071',
  '3072',
  '3101',
  '3107',
  '3168',
  '3169',
  '5060'],
 ['10',
  '16',
  '32',
  '50',
  '165',
  '256',
  '293',
  '296',
  '318',
  '370',
  '457',
  '474',
  '475',
  '552',
  '555',
  '589',
  '593',
  '733',
  '745',
  '762',
  '783',
  '858',
  '1036',
  '1060',
  '1061',
  '1090',
  '1129',
  '1193',
  '1198',
  '1200',
  '1221',
  '1240',
  '1266',
  '1291',
  '1370',
  '1517',
  '1562',
  '1608',
  '1687',
  '1917',
  '2000',
  '2002',
  '2006',
  '2194',
  '2268',
  '2571',
  '2572',
  '2699',
  '2918',
  '2947',
  '2948',
  '2949',
  '2959',
  '2989',
  '2991',
  '2993',
  '3006',
  '3101',
  '3384',
  '3499',
  '3578',
  '3635',
  '3639',
  '3755',
  '3984',
  '4005',
  '4007',
  '5507',
  '6874',
  '7438',
  '7569',
  '8917',
  '32029',
  '32587',
  '33794',
  '41997',
  '43936',
  '44665',
  '49272',
  '53972',
  '54736',
  '58559',
  '59369',
  '63113',
  '68194',
  '69122',
  '69306',
  '74948',
  '78499',
  '78729',
  '79695',
  '81537'],
 ['10',
  '14',
  '21',
  '32',
  '39',
  '47',
  '50',
  '85',
  '151',
  '159',
  '172',
  '231',
  '236',
  '288',
  '296',
  '318',
  '327',
  '342',
  '344',
  '348',
  '434',
  '592'],
 ['158',
  '273',
  '318',
  '531',
  '555',
  '724',
  '910',
  '914',
  '915',
  '916',
  '1086',
  '1104',
  '1234',
  '1343',
  '1513',
  '1947',
  '2080',
  '2407',
  '2739',
  '3668',
  '40819',
  '54259',
  '56367'],
 ['6',
  '9',
  '10',
  '21',
  '32',
  '44',
  '47',
  '70',
  '95',
  '110',
  '112',
  '145',
  '153',
  '163',
  '165',
  '172',
  '173',
  '185',
  '204',
  '208',
  '260',
  '288',
  '293',
  '296',
  '303',
  '315',
  '316',
  '318',
  '349',
  '353',
  '377',
  '379',
  '380',
  '387',
  '393',
  '405',
  '434',
  '442',
  '457',
  '464',
  '474',
  '480',
  '485',
  '494',
  '517',
  '519',
  '521',
  '541',
  '544',
  '555',
  '589',
  '592',
  '648',
  '653',
  '733',
  '736',
  '737',
  '780',
  '786',
  '798',
  '849',
  '858',
  '861',
  '876',
  '980',
  '996',
  '1004',
  '1036',
  '1047',
  '1100',
  '1101',
  '1129',
  '1196',
  '1198',
  '1200',
  '1201',
  '1210',
  '1213',
  '1214',
  '1222',
  '1240',
  '1275',
  '1291',
  '1304',
  '1356',
  '1370',
  '1371',
  '1372',
  '1373',
  '1374',
  '1375',
  '1376',
  '1377',
  '1378',
  '1382',
  '1385',
  '1407',
  '1408',
  '1429',
  '1438',
  '1474',
  '1485',
  '1584',
  '1586',
  '1587',
  '1589',
  '1591',
  '1595',
  '1608',
  '1641',
  '1676',
  '1687',
  '1702',
  '1707',
  '1713',
  '1721',
  '1722',
  '1729',
  '2019'],
 ['293',
  '480',
  '589',
  '858',
  '1201',
  '3793',
  '4369',
  '4638',
  '4896',
  '4993',
  '5349',
  '5903',
  '5952',
  '6377',
  '6539',
  '7153',
  '7458',
  '8368',
  '8636',
  '8961',
  '33679',
  '33794',
  '34150',
  '36529',
  '40815',
  '41569',
  '44191',
  '45499',
  '45720',
  '45722',
  '46530',
  '48780',
  '49272',
  '51662',
  '52722',
  '53125',
  '53464',
  '53996',
  '56171',
  '56174',
  '56367',
  '58559',
  '59315',
  '59784',
  '60040',
  '60069',
  '60684',
  '63859',
  '67255',
  '68319',
  '69526',
  '69844',
  '72378',
  '72641',
  '72998',
  '76093',
  '77561',
  '78499',
  '79132',
  '80463',
  '81591',
  '81834',
  '81845',
  '82461',
  '86332',
  '87232',
  '88125',
  '88140',
  '89745',
  '91529',
  '91630',
  '91658',
  '95510',
  '96079',
  '97938',
  '98809',
  '102125',
  '106489',
  '106920',
  '109487',
  '111759',
  '112852',
  '122892',
  '130634'],
 ['19',
  '350',
  '368',
  '410',
  '442',
  '474',
  '708',
  '786',
  '912',
  '1213',
  '1221',
  '1527',
  '1610',
  '1784',
  '1923',
  '1961',
  '2683',
  '2987',
  '2997',
  '4306'],
 ['32',
  '47',
  '110',
  '170',
  '293',
  '296',
  '318',
  '355',
  '356',
  '455',
  '785',
  '1090',
  '1673',
  '1704',
  '1777',
  '2006',
  '2028',
  '2078',
  '2080',
  '2161',
  '2329',
  '2407',
  '2427',
  '2455',
  '2572',
  '2701',
  '2826',
  '2908',
  '2959',
  '3147',
  '3275',
  '3578',
  '3916',
  '3949',
  '4011',
  '4878',
  '5010',
  '5418',
  '5903',
  '5954',
  '5989',
  '6383',
  '6502',
  '6870',
  '7153',
  '7254',
  '7445',
  '7541',
  '8665',
  '8950',
  '26614',
  '33660',
  '33794',
  '38061',
  '44665',
  '48516',
  '48780',
  '50068',
  '51662',
  '53000',
  '54997',
  '55031',
  '55247',
  '55282',
  '55765',
  '56885',
  '58559',
  '58803',
  '58998',
  '59369',
  '64839',
  '65230',
  '68358',
  '69122',
  '70286',
  '72011',
  '72378',
  '72998',
  '75805',
  '76175'],
 ['1',
  '2',
  '7',
  '10',
  '17',
  '18',
  '21',
  '22',
  '23',
  '29',
  '31',
  '32',
  '34',
  '36',
  '39',
  '45',
  '47',
  '49',
  '50',
  '70',
  '71',
  '76',
  '95',
  '96',
  '107',
  '110',
  '112',
  '117',
  '118',
  '122',
  '141',
  '144',
  '145',
  '147',
  '150',
  '153',
  '158',
  '163',
  '165',
  '178',
  '180',
  '181',
  '185',
  '193',
  '196',
  '198',
  '204',
  '208',
  '215',
  '223',
  '224',
  '225',
  '229',
  '231',
  '232',
  '233',
  '235',
  '247',
  '249',
  '253',
  '260',
  '265',
  '273',
  '277',
  '288',
  '290',
  '291',
  '292',
  '293',
  '296',
  '300',
  '302',
  '305',
  '307',
  '308',
  '316',
  '317',
  '318',
  '320',
  '322',
  '324',
  '327',
  '328',
  '329',
  '333',
  '334',
  '335',
  '337',
  '339',
  '342',
  '344',
  '345',
  '346',
  '347',
  '348',
  '349',
  '350',
  '353',
  '356',
  '357',
  '364',
  '366',
  '367',
  '370',
  '372',
  '380',
  '381',
  '382',
  '412',
  '417',
  '423',
  '425',
  '428',
  '434',
  '441',
  '442',
  '448',
  '454',
  '457',
  '461',
  '464',
  '466',
  '467',
  '469',
  '471',
  '474',
  '475',
  '480',
  '481',
  '482',
  '485',
  '490',
  '492',
  '494',
  '497',
  '500',
  '501',
  '506',
  '507',
  '508',
  '509',
  '512',
  '514',
  '515',
  '527',
  '529',
  '533',
  '534',
  '535',
  '537',
  '538',
  '539',
  '541',
  '543',
  '544',
  '546',
  '549',
  '550',
  '551',
  '552',
  '555',
  '581',
  '585',
  '586',
  '587',
  '588',
  '589',
  '590',
  '593',
  '594',
  '595',
  '597',
  '605',
  '608',
  '612',
  '617',
  '628',
  '647',
  '648',
  '671',
  '678',
  '708',
  '718',
  '720',
  '722',
  '733',
  '736',
  '745',
  '750',
  '761',
  '778',
  '781',
  '786',
  '799',
  '802',
  '804',
  '805',
  '830',
  '832',
  '838',
  '903',
  '912',
  '913',
  '914',
  '919',
  '924',
  '948',
  '953',
  '969',
  '982',
  '986',
  '1020',
  '1028',
  '1035',
  '1036',
  '1037',
  '1041',
  '1061',
  '1079',
  '1080',
  '1081',
  '1086',
  '1089',
  '1092',
  '1094',
  '1095',
  '1097',
  '1101',
  '1120',
  '1124',
  '1127',
  '1129',
  '1136',
  '1148',
  '1171',
  '1173',
  '1175',
  '1179',
  '1183',
  '1186',
  '1187',
  '1188',
  '1190',
  '1193',
  '1196',
  '1197',
  '1198',
  '1199',
  '1200',
  '1206',
  '1208',
  '1210',
  '1214',
  '1215',
  '1216',
  '1218',
  '1220',
  '1223',
  '1225',
  '1231',
  '1236',
  '1240',
  '1241',
  '1243',
  '1246',
  '1249',
  '1250',
  '1253',
  '1255',
  '1256',
  '1257',
  '1259',
  '1261',
  '1265',
  '1266',
  '1268',
  '1269',
  '1270',
  '1274',
  '1277',
  '1278',
  '1279',
  '1282',
  '1284',
  '1285',
  '1289',
  '1291',
  '1292',
  '1296',
  '1298',
  '1301',
  '1306',
  '1307',
  '1320',
  '1321',
  '1339',
  '1342',
  '1343',
  '1347',
  '1353',
  '1356',
  '1358',
  '1366',
  '1367',
  '1370',
  '1371',
  '1372',
  '1374',
  '1376',
  '1377',
  '1378',
  '1385',
  '1387',
  '1391',
  '1393',
  '1395',
  '1396',
  '1407',
  '1411',
  '1425',
  '1429',
  '1438',
  '1475',
  '1479',
  '1483',
  '1496',
  '1515',
  '1517',
  '1527',
  '1544',
  '1552',
  '1554',
  '1562',
  '1566',
  '1569',
  '1573',
  '1580',
  '1585',
  '1597',
  '1633',
  '1639'],
 ['32',
  '82',
  '101',
  '149',
  '150',
  '159',
  '230',
  '247',
  '260',
  '293',
  '296',
  '306',
  '307',
  '308',
  '370',
  '527',
  '529',
  '608',
  '728',
  '750',
  '778',
  '852',
  '858',
  '924',
  '1054',
  '1173',
  '1190',
  '1196',
  '1199',
  '1206',
  '1208',
  '1210',
  '1211',
  '1213',
  '1217',
  '1218',
  '1219',
  '1220',
  '1221',
  '1222',
  '1225',
  '1228',
  '1230',
  '1232',
  '1233',
  '1236',
  '1237',
  '1245',
  '1246',
  '1247',
  '1248',
  '1251',
  '1258',
  '1260',
  '1263',
  '1264',
  '1274',
  '1276',
  '1277',
  '1280',
  '1283',
  '1285',
  '1288',
  '1289',
  '1298',
  '1307',
  '1320',
  '1321',
  '1345',
  '1349',
  '1350',
  '1354',
  '1355',
  '1358',
  '1367',
  '1370',
  '1377',
  '1387',
  '1407',
  '1517',
  '1810',
  '1840',
  '1904',
  '1952',
  '1953',
  '1982',
  '2012',
  '2115',
  '2131',
  '2174',
  '2291',
  '2318',
  '2324',
  '2395',
  '2513',
  '2514',
  '2594',
  '2599',
  '2628',
  '2640',
  '2683',
  '2706',
  '2712',
  '2726',
  '2730',
  '2731',
  '2857',
  '2858',
  '2959',
  '3030',
  '3081',
  '3083',
  '3089',
  '3160',
  '3272',
  '3500',
  '3504',
  '3645',
  '3683',
  '3735',
  '3741',
  '3852',
  '3911',
  '3949',
  '3977',
  '3996',
  '4017',
  '4034',
  '4226',
  '4641',
  '4718',
  '4848',
  '4878',
  '4881',
  '4914',
  '5010',
  '5146',
  '5147',
  '5225',
  '5378',
  '5478',
  '5608',
  '5673',
  '5690',
  '5878',
  '5902',
  '5940',
  '5954',
  '5989',
  '5995',
  '6242',
  '6301',
  '6331',
  '6335',
  '6440',
  '6537',
  '6559',
  '6666'],
 ['150',
  '153',
  '165',
  '185',
  '208',
  '231',
  '253',
  '288',
  '292',
  '296',
  '316',
  '318',
  '329',
  '339',
  '344',
  '349',
  '356',
  '367',
  '380',
  '434',
  '457',
  '588',
  '589',
  '590',
  '592',
  '593'],
 ['24',
  '339',
  '785',
  '908',
  '968',
  '1127',
  '1193',
  '1196',
  '1307',
  '1393',
  '1513',
  '1623',
  '1642',
  '1911',
  '2013',
  '2037',
  '2355',
  '2392',
  '2396',
  '2428',
  '2490',
  '2541',
  '2546',
  '2572',
  '2581',
  '2598',
  '2605',
  '2629',
  '2672',
  '2676',
  '2683',
  '2688',
  '2694',
  '2699',
  '2701',
  '2702',
  '2706',
  '2712',
  '2713',
  '2716',
  '2722',
  '2724',
  '2761',
  '2762',
  '2770',
  '2771',
  '2806',
  '2827',
  '2840',
  '2841',
  '2858',
  '2861',
  '2881',
  '2907',
  '2908',
  '2987',
  '2995',
  '3005',
  '3081',
  '3155',
  '3157',
  '3174',
  '3176',
  '3273',
  '3300',
  '3408',
  '3453',
  '3512',
  '3534',
  '3578',
  '3617',
  '3653',
  '3664',
  '3752',
  '3753',
  '3798',
  '3824',
  '3857',
  '3908',
  '3916',
  '3956',
  '3977',
  '3988',
  '4022',
  '4233',
  '4299',
  '4308',
  '4310'],
 ['239',
  '260',
  '480',
  '569',
  '588',
  '595',
  '671',
  '741',
  '908',
  '912',
  '919',
  '923',
  '1196',
  '1197',
  '1198',
  '1203',
  '1210',
  '1259',
  '1269',
  '1270',
  '1274',
  '1275',
  '1282',
  '1291',
  '1566',
  '1688',
  '1920',
  '1921',
  '2081',
  '2092',
  '2294',
  '2355',
  '2687',
  '2692',
  '2761',
  '2987',
  '3000',
  '3034',
  '3745',
  '3793',
  '3863',
  '3996',
  '4016',
  '4027',
  '4090',
  '4148',
  '4306',
  '4446',
  '4519',
  '4993',
  '5072',
  '5146',
  '5349',
  '5361',
  '5465',
  '5608',
  '5618',
  '5952'],
 ['32',
  '97',
  '165',
  '256',
  '296',
  '307',
  '318',
  '356',
  '364',
  '471',
  '480',
  '588',
  '589',
  '595',
  '608',
  '709',
  '733',
  '778',
  '780',
  '830',
  '910',
  '913',
  '955',
  '1034',
  '1036',
  '1064',
  '1097',
  '1104',
  '1198',
  '1223',
  '1249',
  '1265',
  '1285',
  '1370',
  '1408',
  '1732',
  '1784',
  '1876',
  '1920',
  '2321',
  '2496',
  '2599',
  '2770',
  '2858',
  '2959',
  '2997',
  '3000',
  '3155',
  '3535',
  '3645',
  '4061',
  '4246',
  '4306',
  '4886',
  '4914',
  '4973',
  '5349',
  '5446',
  '5618',
  '6016',
  '6377',
  '6440',
  '6743',
  '8360',
  '8961',
  '8969',
  '32587',
  '46578',
  '50872',
  '53972',
  '55820',
  '56367',
  '57669',
  '58559',
  '60069',
  '63082',
  '68954',
  '71535',
  '73344',
  '76251'],
 ['2',
  '3',
  '11',
  '19',
  '36',
  '39',
  '47',
  '50',
  '69',
  '110',
  '111',
  '141',
  '150',
  '153',
  '175',
  '194',
  '223',
  '231',
  '247',
  '253',
  '260',
  '265',
  '266',
  '288',
  '292',
  '296',
  '300',
  '316',
  '318',
  '329',
  '344',
  '353',
  '356',
  '357',
  '364',
  '370',
  '377',
  '380',
  '408',
  '440',
  '457',
  '471',
  '477',
  '480',
  '500',
  '508',
  '515',
  '520',
  '527',
  '534',
  '539',
  '541',
  '551',
  '553',
  '585',
  '586',
  '588',
  '589',
  '590',
  '592',
  '593',
  '595',
  '597',
  '608',
  '627',
  '648',
  '733',
  '736',
  '785',
  '788',
  '913',
  '919',
  '920',
  '923',
  '1036',
  '1049',
  '1079',
  '1080',
  '1089',
  '1090',
  '1094',
  '1097',
  '1127',
  '1136',
  '1196',
  '1197',
  '1198',
  '1200',
  '1203',
  '1208',
  '1210',
  '1213',
  '1214',
  '1219',
  '1222',
  '1240',
  '1246',
  '1252',
  '1258',
  '1259',
  '1265',
  '1266',
  '1278',
  '1285',
  '1289',
  '1291',
  '1307',
  '1320',
  '1339',
  '1343',
  '1356',
  '1358',
  '1370',
  '1372',
  '1374',
  '1375',
  '1376',
  '1380',
  '1391',
  '1407',
  '1449',
  '1476',
  '1517',
  '1580',
  '1584',
  '1610',
  '1617',
  '1625',
  '1676',
  '1682',
  '1690',
  '1721',
  '1747',
  '1784',
  '1883',
  '1923',
  '1961',
  '1962',
  '1968',
  '2000',
  '2005',
  '2006',
  '2028',
  '2064',
  '2081',
  '2116',
  '2124',
  '2208',
  '2291',
  '2300',
  '2355',
  '2391',
  '2393',
  '2395',
  '2406',
  '2407',
  '2423',
  '2467',
  '2499',
  '2571',
  '2583',
  '2628',
  '2640',
  '2641',
  '2683',
  '2706',
  '2710',
  '2716',
  '2791',
  '2792',
  '2795',
  '2804',
  '2858',
  '2916',
  '2944',
  '2987',
  '3000',
  '3040',
  '3052',
  '3072',
  '3081',
  '3142',
  '3147',
  '3175',
  '3254',
  '3258',
  '3260',
  '3361',
  '3396',
  '3397',
  '3418',
  '3421',
  '3448',
  '3450',
  '3499',
  '3552',
  '3555',
  '3578',
  '3668',
  '3671',
  '3712',
  '3751',
  '3755',
  '3760',
  '3785',
  '3809',
  '3844',
  '3868',
  '3897',
  '3911',
  '3948',
  '3950',
  '3967',
  '3994',
  '4027',
  '4029',
  '4033',
  '4034',
  '4039',
  '4041',
  '4102',
  '4128',
  '4159',
  '4226',
  '4262',
  '4306',
  '4321',
  '4678',
  '4720',
  '4855',
  '4979',
  '4993',
  '5010',
  '5013',
  '5060',
  '5110',
  '5225',
  '5265',
  '5299',
  '5378',
  '5418',
  '5444',
  '5445',
  '5464',
  '5481',
  '5572',
  '5669',
  '5944',
  '5945',
  '5952',
  '5971',
  '5989',
  '6002',
  '6296',
  '6333',
  '6367',
  '6535',
  '6807',
  '6874',
  '6936',
  '6942',
  '7090',
  '7153',
  '7361',
  '8014',
  '8366',
  '8622',
  '8865',
  '8872',
  '48385'],
 ['6',
  '7',
  '16',
  '28',
  '39',
  '47',
  '50',
  '62',
  '145',
  '161',
  '165',
  '186',
  '193',
  '256',
  '265',
  '293',
  '315',
  '316',
  '317',
  '318',
  '339',
  '349',
  '353',
  '356',
  '364',
  '367',
  '377',
  '380',
  '440',
  '454',
  '457',
  '474',
  '480',
  '494',
  '500',
  '508',
  '527',
  '539',
  '586',
  '587',
  '588',
  '597',
  '608',
  '628',
  '708',
  '733',
  '786',
  '805',
  '832',
  '858',
  '899',
  '908',
  '923',
  '1028',
  '1036',
  '1047',
  '1073',
  '1088',
  '1188',
  '1198',
  '1203',
  '1221',
  '1222',
  '1235',
  '1242',
  '1246',
  '1259',
  '1270',
  '1271',
  '1285',
  '1291',
  '1302',
  '1370',
  '1380',
  '1393',
  '1396',
  '1407',
  '1466',
  '1485',
  '1500',
  '1513',
  '1552',
  '1569',
  '1580',
  '1608',
  '1625',
  '1704',
  '1721',
  '1784',
  '1876',
  '1917',
  '1918',
  '1961',
  '1968',
  '2000',
  '2001',
  '2002',
  '2011',
  '2012',
  '2028',
  '2054',
  '2081',
  '2100',
  '2115',
  '2144',
  '2150',
  '2186',
  '2248',
  '2278',
  '2321',
  '2329',
  '2336',
  '2353',
  '2396',
  '2424',
  '2455',
  '2501',
  '2502',
  '2539',
  '2571',
  '2572',
  '2617',
  '2671',
  '2710',
  '2762',
  '2763',
  '2797',
  '2858',
  '2881',
  '2890',
  '2918',
  '2959',
  '3006',
  '3020',
  '3039',

In [ ]:
model = Word2Vec(window = 10, sg = 1, hs = 0,
                 negative = 10, 
                 alpha=0.03, min_alpha=0.0007,
                 seed = 14)
model.build_vocab(watch_train, progress_per=200)
model.train(watch_train, total_examples = model.corpus_count, 
            epochs=10, report_delay=1)

ImportError: cannot import name 'triu' from 'scipy.linalg.special_matrices' (/root/miniforge3/lib/python3.12/site-packages/scipy/linalg/special_matrices.py)

In [ ]:
X = model[model.wv.vocab]
X.shape

AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

In [ ]:
%pip install gensim==3.8.1

Collecting gensim==3.8.1
  Downloading gensim-3.8.1.tar.gz (23.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.4/23.4 MB 4.2 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.11.3 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.26.4)
Requirement already satisfied: scipy>=0.18.1 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.13.1)
Requirement already satisfied: six>=1.5.0 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (1.17.0)
Requirement already satisfied: smart_open>=1.8.1 in /root/miniforge3/lib/python3.12/site-packages (from gensim==3.8.1) (7.3.0.post1)
Requirement already satisfied: wrapt in /root/miniforge3/lib/python3.12/site-packages (from smart_open>=1.8.1->gensim==3.8.1) (1.17.2)
Building wheels for collected packages: gensim
  DEPRECATION: Building 'gensim' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'gensim'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for gensim (setup.py) ... done
  Created wheel for gensim: filename=gensim-3.8.1-cp312-cp312-linux_x86_64.whl size=23720133 sha256=ab8d537f1246dd7483b7579f39bab037cbbbc1398fadb39d0670767a56c54910
  Stored in directory: /root/.cache/pip/wheels/12/70/82/9d341e4452f68a12ccdcb2d4d2f749b321ee4ba0ce84db270c
Successfully built gensim
Installing collected packages: gensim
  Attempting uninstall: gensim
    Found existing installation: gensim 4.3.3
    Uninstalling gensim-4.3.3:
      Successfully uninstalled gensim-4.3.3
Successfully installed gensim-3.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
watch = train_df[["movieId", "title"]]
# remove duplicates
watch.drop_duplicates(inplace=True, subset='movieId', keep="last")
# create movie id and tittle dictionary
watch_dict = watch.groupby('movieId')['title'].apply(list).to_dict()

In [ ]:
watch_dict

{'1': ['Toy Story (1995)'],
 '10': ['GoldenEye (1995)'],
 '100': ['City Hall (1996)'],
 '1000': ['Curdled (1996)'],
 '100036': ['Crossfire Hurricane (2012)'],
 '100083': ['Movie 43 (2013)'],
 '100091': ["Hitler's Madman (1943)"],
 '100106': ["Pervert's Guide to Ideology, The (2012)"],
 '100108': ['Parker (2013)'],
 '100138': ['Simple Life, A (Tao jie) (2011)'],
 '100159': ['Sightseers (2012)'],
 '100163': ['Hansel & Gretel: Witch Hunters (2013)'],
 '100165': ['Kon-Tiki (1950)'],
 '100169': ['After Porn Ends (2010)'],
 '100238': ["Big Picture, The (L'homme qui voulait vivre sa vie) (2010)"],
 '100240': ["Woman's Face, A (En kvinnas ansikte) (1938)"],
 '100244': ['East, The (2013)'],
 '1003': ['Extreme Measures (1996)'],
 '100304': ['Liability, The (2012)'],
 '100308': ['Pressure Point  (1962)'],
 '100322': ['Baytown Outlaws, The (2012)'],
 '100326': ['Stand Up Guys (2012)'],
 '100344': ['No (2012)'],
 '100383': ['Side Effects (2013)'],
 '100385': ["Midnight's Children (2012)"],
 '100390': ['Identity Thief (2013)'],
 '1004': ['Glimmer Man, The (1996)'],
 '100436': ['Gatekeepers, The (2012)'],
 '100440': ['Lore (2012)'],
 '100487': ['Beautiful Creatures (2013)'],
 '100498': ['Good Day to Die Hard, A (2013)'],
 '1005': ['D3: The Mighty Ducks (1996)'],
 '100507': ['21 and Over (2013)'],
 '100527': ['Safe Haven (2013)'],
 '100556': ['Act of Killing, The (2012)'],
 '100579': ['Universal Soldier: Day of Reckoning (2012)'],
 '1006': ['Chamber, The (1996)'],
 '1007': ['Apple Dumpling Gang, The (1975)'],
 '100714': ['Before Midnight (2013)'],
 '100717': ['Oranges, The (2011)'],
 '100737': ['Snitch (2013)'],
 '100745': ['TPB AFK: The Pirate Bay Away from Keyboard (2013)'],
 '1008': ['Davy Crockett, King of the Wild Frontier (1955)'],
 '100810': ['Dark Skies (2013)'],
 '100882': ['Journey to the West: Conquering the Demons (Daai wa sai you chi Chui mo chun kei) (2013)'],
 '1009': ['Escape to Witch Mountain (1975)'],
 '100906': ['Maniac Cop 2 (1990)'],
 '101': ['Bottle Rocket (1996)'],
 '1010': ['Love Bug, The (1969)'],
 '101025': ['Jack the Giant Slayer (2013)'],
 '101060': ['Last Exorcism Part II, The (2013)'],
 '101064': ['Verboten! (1959)'],
 '101076': ['G.I. Joe: Retaliation (2013)'],
 '101088': ['Stoker (2013)'],
 '1011': ['Herbie Rides Again (1974)'],
 '101112': ['Oz the Great and Powerful (2013)'],
 '101137': ['Dead Man Down (2013)'],
 '101142': ['Croods, The (2013)'],
 '1012': ['Old Yeller (1957)'],
 '101204': ['Hucksters, The (1947)'],
 '101207': ['Emperor (2012)'],
 '101210': ['Silence, The (Das letzte Schweigen) (2010)'],
 '101283': ['Incredible Burt Wonderstone, The (2013)'],
 '101285': ['Spring Breakers (2013)'],
 '1013': ['Parent Trap, The (1961)'],
 '101360': ['Call, The (2013)'],
 '101362': ['Olympus Has Fallen (2013)'],
 '1014': ['Pollyanna (1960)'],
 '101433': ['Moving Out (1983)'],
 '1015': ['Homeward Bound: The Incredible Journey (1993)'],
 '101525': ['Place Beyond the Pines, The (2012)'],
 '101529': ['Brass Teapot, The (2012)'],
 '101531': ['Phil Spector (2013)'],
 '1016': ['Shaggy Dog, The (1959)'],
 '101612': ['Admission (2013)'],
 '101687': ['Blue Caprice (2013)'],
 '1017': ['Swiss Family Robinson (1960)'],
 '101739': ['Evil Dead (2013)'],
 '101741': ['Trance (2013)'],
 '101761': ['Welcome to the Punch (2013)'],
 '1018': ['That Darn Cat! (1965)'],
 '101862': ['50 Children: The Rescue Mission of Mr. And Mrs. Kraus (2013)'],
 '101864': ['Oblivion (2013)'],
 '101893': ['To the Wonder (2013)'],
 '101895': ['42 (2013)'],
 '1019': ['20,000 Leagues Under the Sea (1954)'],
 '101904': ['Happy (2011)'],
 '101962': ['Wolf Children (Okami kodomo no ame to yuki) (2012)'],
 '101971': ['Never Sleep Again: The Elm Street Legacy (2010)'],
 '101973': ['Disconnect (2012)'],
 '101997': ['Scary Movie 5 (Scary MoVie) (2013)'],
 '102': ['Mr. Wrong (1996)'],
 '1020': ['Cool Runnings (1993)'],
 '102033': ['Pain & Gain (2013)'],
 '102047': ['Bride Came C.O.D., The (1941)'],
 '102066': ['Resolution (2012)'],
 '102070': ['Grabbers (2012)'],
 '102084': ['Justice League: Doom (2012)'],
 '102088': ['Grandmaster, The (Yi dai zong shi) (2013)'],
 '102093': ['After Office Hours (1935)'],
 '1021': ['Angels in the Outfield (1994)'],
 '102123': ['This Is the End (2013)'],
 '102125': ['Iron Man 3 (2013)'],
 '102160': ['Numbers Station, The (2013)'],
 '102194': ['Mud (2012)'],
 '1022': ['Cinderella (1950)'],
 '102231': ['Dragon (Wu Xia) (2011)'],
 '102275': ['Afflicted, The (2010)'],
 '102278': ['Pawn (2013)'],
 '102294': ['Scapegoat, The (2012)'],
 '1023': ['Winnie the Pooh and the Blustery Day (1968)'],
 '102354': ['About Cherry (2012)'],
 '102378': ['Syrup (2013)'],
 '102396': ['Woman in the Fifth, The (Femme du Vème, La) (2011)'],
 '1024': ['Three Caballeros, The (1945)'],
 '102407': ['Great Gatsby, The (2013)'],
 '102432': ['Blueprint for Murder, A (1953)'],
 '102445': ['Star Trek Into Darkness (2013)'],
 '102481': ['Internship, The (2013)'],
 '102487': ['Man with a Cloak, The (1951)'],
 '1025': ['Sword in the Stone, The (1963)'],
 '102509': ['Secret Six, The (1931)'],
 '102666': ['Ivan Vasilievich: Back to the Future (Ivan Vasilievich menyaet professiyu) (1973)'],
 '102684': ['Only God Forgives (2013)'],
 '102686': ['Hangover Part III, The (2013)'],
 '102688': ['Garbo the Spy (Garbo: El espía) (2009)'],
 '1027': ['Robin Hood: Prince of Thieves (1991)'],
 '102716': ['Fast & Furious 6 (Fast and the Furious 6, The) (2013)'],
 '102720': ['Epic (2013)'],
 '102753': ['Past, The (Le passé) (2013)'],
 '102760': ['Down Terrace (2009)'],
 '1028': ['Mary Poppins (1964)'],
 '102800': ['Frances Ha (2012)'],
 '102819': ['Behind the Candelabra (2013)'],
 '102868': ['Privilege (1967)'],
 '102880': ['After Earth (2013)'],
 '1029': ['Dumbo (1941)'],
 '102903': ['Now You See Me (2013)'],
 '102920': ['Dark Circles (2013)'],
 '102967': ["Combat dans L'Ile, Le (Fire and Ice) (1962)"],
 '102978': ['Mary and Martha (2013)'],
 '102991': ['Berberian Sound Studio (2012)'],
 '102993': ['Way, Way Back, The (2013)'],
 '103': ['Unforgettable (1996)'],
 '1030': ["Pete's Dragon (1977)"],
 '103006': ['Penthouse (1933)'],
 '103027': ['Much Ado About Nothing (2012)'],
 '103042': ['Man of Steel (2013)'],
 '103055': ['The Big Wedding (2013)'],
 '103075': ['Purge, The (2013)'],
 '1031': ['Bedknobs and Broomsticks (1971)'],
 '103107': ['20 Feet from Stardom (Twenty Feet from Stardom) (2013)'],
 '103137': ['Bling Ring, The (2013)'],
 '103141': ['Monsters University (2013)'],
 '1032': ['Alice in Wonderland (1951)'],
 '103210': ['Fullmetal Alchemist: The Sacred Star of Milos (2011)'],
 '103219': ['Maniac (2012)'],
 '103228': ['Pacific Rim (2013)'],
 '103235': ['Best Offer, The (Migliore offerta, La) (2013)'],
 '103249': ['World War Z (2013)'],
 '103253': ['Elysium (2013)'],
 '103279': ['What Maisie Knew (2012)'],
 '103299': ['American Mary (2012)'],
 '1033': ['Fox and the Hound, The (1981)'],
 '103306': ['Europa Report (2013)'],
 '103315': ['Odd Thomas (2013)'],
 '103319': ['Jim Gaffigan: Mr. Universe (2012)'],
 '103335': ['Despicable Me 2 (2013)'],
 '103339': ['White House Down (2013)'],
 '103341': ["World's End, The (2013)"],
 '103366': ['Redemption (Hummingbird) (2013)'],
 '103372': ['Heat, The (2013)'],
 '103384': ['Lone Ranger, The (2013)'],
 '1034': ['Freeway (1996)'],
 '103439': ['Thieves, The (Dodookdeul) (2012)'],
 '103444': ['Woody Allen: A Documentary (2012)'],
 '103483': ['V/H/S/2 (2013)'],
 '103493': ["Gideon's Army (2013)"],
 '1035': ['Sound of Music, The (1965)'],
 '103539': ['The Spectacular Now (2013)'],
 '103554': ['Hijacking, A (Kapringen) (2012)'],
 '103570': ["Dead Man's Burden (2012)"],
 '103572': ['Downloaded (2013)'],
 '103574': ['Jug Face (2013)'],
 '103596': ['Sharknado (2013)'],
 '1036': ['Die Hard (1988)'],
 '103624': ['Fruitvale Station (2013)'],
 '103655': ['R.I.P.D. (2013)'],
 '103659': ['Justice League: The Flashpoint Paradox (2013)'],
 '103669': ['Killing Season (2013)'],
 '103688': ['Conjuring, The (2013)'],
 '1037': ['Lawnmower Man, The (1992)'],
 '103755': ['Turbo (2013)'],
 '103772': ['Wolverine, The (2013)'],
 '1038': ['Unhook the Stars (1996)'],
 '103801': ['Drinking Buddies (2013)'],
 '103810': ['Red 2 (2013)'],
 '103823': ['Nick Carter, Master Detective (1939)'],
 '103825': ['Vehicle 19 (2013)'],
 '103849': ['New World (Shin-sae-gye) (2013)'],
 '103851': ['Page Miss Glory (1935)'],
 '103865': ['Revenge for Jolly! (2012)'],
 '103867': ['Night Train To Lisbon (2013)'],
 '103883': ['2 Guns (2013)'],
 '103980': ['Blue Jasmine (2013)'],
 '103984': ['Great Beauty, The (Grande Bellezza, La) (2013)'],
 '104': ['Happy Gilmore (1996)'],
 '1040': ['Secret Agent, The (1996)'],
 '104033': ['Love, Marilyn (2012)'],
 '104069': ['Louis C.K.: Oh My God (2013)'],
 '104074': ['Percy Jackson: Sea of Monsters (2013)'],
 '104078': ['Alan Partridge: Alpha Papa (2013)'],
 '104093': ['Attack, The (2012)'],
 '104099': ['Lupin the Third: The Secret of Mamo (1978)'],
 '1041': ['Secrets & Lies (1996)'],
 '104116': ['Road to Brown, The (1989)'],
 '104129': ['Man of Tai Chi (2013)'],
 '104155': ['Clear History (2013)'],
 '104177': ['From One Second to the Next (2013)'],
 '1042': ['That Thing You Do! (1996)'],
 '104211': ["We're the Millers (2013)"],
 '104218': ['Grown Ups 2 (2013)'],
 '104231': ['Drug War (Du zhan) (2012)'],
 '104241': ['Kick-Ass 2 (2013)'],
 '104243': ['Riddick (2013)'],
 '104272': ['Blackfish (2013)'],
 '104280': ['Black Room, The (1935)'],
 '104283': ['Wind Rises, The (Kaze tachinu) (2013)'],
 '1043': ['To Gillian on Her 37th Birthday (1996)'],
 '104312': ['Mortal Instruments: City of Bones, The (2013)'],
 '104319': ['First Grader, The (2010)'],
 '104323': ['Four Horsemen (2012)'],
 '104337': ["Lee Daniels' The Butler (2013)"],
 '104356': ['Museum Hours (2013)'],
 '104361': ["Ain't Them Bodies Saints (2013)"],
 '104374': ['About Time (2013)'],
 '1044': ['Surviving Picasso (1996)'],
 '104406': ["Fill the Void (Lemale et ha'halal) (2012)"],
 '104419': ['Justice League: Crisis on Two Earths (2010)'],
 '104441': ['Frozen Ground, The (2013)'],
 '104457': ["You're Next (2011)"],
 '104520': ['Crimson Permanent Assurance, The (1983)'],
 '104563': ['Too Hot to Handle (1938)'],
 '1046': ['Beautiful Thing (1996)'],
 '104642': ['Sealed Cargo (1951)'],
 '1047': ['Long Kiss Goodnight, The (1996)'],
 '104736': ['Closed Circuit (2013)'],
 '104762': ['Teacher, A (2013)'],
 '104841': ['Gravity (2013)'],
 '104843': ['And Now a Word from Our Sponsor (2013)'],
 '104861': ['I Spit on Your Grave 2 (2013)'],
 '104879': ['Prisoners (2013)'],
 '104881': ['Out of the Furnace (Dust to Dust) (Low Dweller, The) (2013)'],
 '1049': ['Ghost and the Darkness, The (1996)'],
 '104906': ['Austenland (2013)'],
 '104908': ['Insidious: Chapter 2 (2013)'],
 '104913': ['Rush (2013)'],
 '104925': ['Family, The (2013)'],
 '104944': ['Short Term 12 (2013)'],
 '104947': ['At Any Price (2012)'],
 '104956': ['Just One of the Girls (1993)'],
 '105': ['Bridges of Madison County, The (1995)'],
 '1050': ['Looking for Richard (1996)'],
 '1051': ['Trees Lounge (1996)'],
 '105197': ['Nebraska (2013)'],
 '105211': ['Enough Said (2013)'],
 '105213': ['Don Jon (2013)'],
 '105223': ['Colorado Territory (1949)'],
 '105266': ['First Cousin Once Removed (2012)'],
 '105351': ['Runner Runner (2013)'],
 '105355': ["Blue Is the Warmest Color (La vie d'Adèle) (2013)"],
 '105366': ['Shake Hands with the Devil (1959)'],
 '105386': ["Curse of Chucky (Child's Play 6) (2013)"],
 '1054': ['Get on the Bus (1996)'],
 '105404': ["Muhammad Ali's Greatest Fight (2013)"],
 '105468': ['Cloudy with a Chance of Meatballs 2 (2013)'],
 '105477': ['Talaash (2012)'],
 '105497': ['Kumail Nanjiani: Beta Male (2013)'],
 '105504': ['Captain Phillips (2013)'],
 '105593': ['Filth (2013)'],
 '1056': ['Jude (1996)'],
 '105653': ['Escape Plan (2013)'],
 '1057': ['Everyone Says I Love You (1996)'],
 '105703': ['Haute Cuisine (2012)'],
 '105720': ['Thief of Paris, The (Le voleur) (1967)'],
 '105731': ['Carrie (2013)'],
 '105748': ["Place of One's Own, A (1945)"],
 '105755': ['Counselor, The (2013)'],
 '1058': ['Bitter Sugar (Azúcar amarga) (1996)'],
 '105835': ['Double, The (2013)'],
 '105844': ['12 Years a Slave (2013)'],
 '105863': ["Child's Pose (2013)"],
 '1059': ["William Shakespeare's Romeo + Juliet (1996)"],
 '105954': ['All Is Lost (2013)'],
 '1060': ['Swingers (1996)'],
 '106002': ["Ender's Game (2013)"],
 '106026': ['Folies Bergere de Paris (1935)'],
 '106046': ['The Escape Artist (1982)'],
 '106062': ['Jackass Presents: Bad Grandpa (2013)'],
 '106072': ['Thor: The Dark World (2013)'],
 '1061': ['Sleepers (1996)'],
 '106100': ['Dallas Buyers Club (2013)'],
 '106144': ['Selfish Giant, The (2013)'],
 '106163': ['Touch of Sin, A (Tian zhu ding) (2013)'],
 '106193': ['Les Formidables (Gang-jeok) (2006)'],
 '106195': ['How I Live Now (2013)'],
 '106220': ['Aziz Ansari: Buried Alive (2013)'],
 '106222': ['Aziz Ansari: Dangerously Delicious (2012)'],
 '106234': ['Great Expectations (2012)'],
 '106240': ['Free Birds (2013)'],
 '1063': ['Johns (1996)'],
 '106330': ['Last Vegas (2013)'],
 '106334': ['Hollow Crown, The (2012)'],
 '106346': ['W.C. Fields and Me (1976)'],
 '1064': ['Aladdin and the King of Thieves (1996)'],
 '106407': ['Seduced and Abandoned (2013)'],
 '106438': ['Philomena (2013)'],
 '106441': ['Book Thief, The (2013)'],
 '106452': ['Ida (2013)'],
 '106487': ['Hunger Games: Catching Fire, The (2013)'],
 '106489': ['Hobbit: The Desolation of Smaug, The (2013)'],
 '106491': ['47 Ronin (2013)'],
 '106498': ['Magic Voyage of Sindbad, The (Sadko) (1953)'],
 '106508': ["Dyatlov Pass Incident, The (Devil's Pass) (2013)"],
 '106583': ['Berlin Express (1948)'],
 '1066': ['Shall We Dance (1937)'],
 '106642': ['Day of the Doctor, The (2013)'],
 '106696': ['Frozen (2013)'],
 '1067': ['Damsel in Distress, A (1937)'],
 '106766': ['Inside Llewyn Davis (2013)'],
 '106782': ['Wolf of Wall Street, The (2013)'],
 '106785': ['Homefront (2013)'],
 '1068': ['Crossfire (1947)'],
 '106839': ['Mandela: Long Walk to Freedom (2013)'],
 '106841': ['August: Osage County (2013)'],
 '106873': ['Evangelion: 3.0 You Can (Not) Redo (2012)'],
 '106883': ['All is Bright (2013)'],
 '1069': ['Murder, My Sweet (1944)'],
 '106916': ['American Hustle (2013)'],
 '106918': ['Secret Life of Walter Mitty, The (2013)'],
 '106920': ['Her (2013)'],
 '107': ['Muppet Treasure Island (1996)'],
 '1070': ['Macao (1952)'],
 '107042': ['Six by Sondheim (2013)'],
 '107069': ['Lone Survivor (2013)'],
 '1071': ['For the Moment (1994)'],
 '107141': ['Saving Mr. Banks (2013)'],
 '107159': ['Zatoichi and the Chest of Gold (Zatôichi senryô-kubi) (Zatôichi 6) (1964)'],
 '107196': ['Is the Man Who Is Tall Happy? (2013)'],
 '1073': ['Willy Wonka & the Chocolate Factory (1971)'],
 '107314': ['Oldboy (2013)'],
 '107348': ['Anchorman 2: The Legend Continues (2013)'],
 '107406': ['Snowpiercer (2013)'],
 '1076': ['Innocents, The (1961)'],
 '107677': ['Human Race, The (2013)'],
 '1077': ['Sleeper (1973)'],
 '107765': ['Dream Machine (1991)'],
 '107771': ['Only Lovers Left Alive (2013)'],
 '1078': ['Bananas (1971)'],
 '1079': ['Fish Called Wanda, A (1988)'],
 '107916': ['Yves Saint Laurent (2014)'],
 '107949': ['Invisible Woman, The (2013)'],
 '107978': ['Like Father, Like Son (Soshite chichi ni naru) (2013)'],
 '107980': ['Railway Man, The (2013)'],
 '107990': ['We and the I, The (2012)'],
 '107997': ['We Are What We Are (2013)'],
 '108': ['Catwalk (1996)'],
 '1080': ["Monty Python's Life of Brian (1979)"],
 '108078': ['Chinese Puzzle (Casse-tête chinois) (2013)'],
 '1081': ['Victor/Victoria (1982)'],
 '108156': ['Ride Along (2014)'],
 '108158': ['Penguin Pool Murder (1932)'],
 '108188': ['Jack Ryan: Shadow Recruit (2014)'],
 '108190': ['Divergent (2014)'],
 '108192': ["Hotel Chevalier (Part 1 of 'The Darjeeling Limited') (2007)"],
 '1082': ['Candidate, The (1972)'],
 '108216': ['Cargo (2013)'],
 '108220': ['Square, The (Al Midan) (2013)'],
 '1083': ['Great Race, The (1965)'],
 '108318': ['Single Shot, A (2013)'],
 '1084': ['Bonnie and Clyde (1967)'],
 '108427': ['Blume in Love (1973)'],
 '1085': ['Old Man and the Sea, The (1958)'],
 '108501': ['Justice League: War (2014)'],
 '108506': ['Dark Touch (2013)'],
 '108548': ['Big Bang Theory, The (2007)'],
 '108583': ['Fawlty Towers (1975-1979)'],
 '1086': ['Dial M for Murder (1954)'],
 '1087': ['Madame Butterfly (1995)'],
 '108713': ['Tomorrow Night (1998)'],
 '108715': ['Better Living Through Chemistry (2014)'],
 '108727': ['Nymphomaniac: Volume I (2013)'],
 '108729': ['Enemy (2013)'],
 '108778': ["Stranger by the Lake (L'inconnu du lac) (2013)"],
 '108780': ['Labor Day (2013)'],
 '1088': ['Dirty Dancing (1987)'],
 '108825': ["Young and Prodigious T.S. Spivet, The (L'extravagant voyage du jeune et prodigieux T.S. Spivet) (2013)"],
 '108864': ['Prey, The (La proie) (2011)'],
 '108899': ['Gloria (2013)'],
 '1089': ['Reservoir Dogs (1992)'],
 '108928': ['Monuments Men, The (2014)'],
 '108932': ['The Lego Movie (2014)'],
 '108938': ['Aliyah (Alyah) (2012)'],
 '108940': ['Road, The (2011)'],
 '108945': ['RoboCop (2014)'],
 '108949': ['Art of the Steal, The (2013)'],
 '108977': ['Paranoia Agent (2004)'],
 '108979': ['Cowboy Bebop (1998)'],
 '108981': ['Nymphomaniac: Volume II (2013)'],
 '1090': ['Platoon (1986)'],
 '109072': ['Sabotage (2014)'],
 '1091': ["Weekend at Bernie's (1989)"],
 '109157': ['Long Way Down, A (2014)'],
 '109191': ["Winter's Tale (2014)"],
 '1092': ['Basic Instinct (1992)'],
 '109237': ['Bhowani Junction (1956)'],
 '1093': ['Doors, The (1991)'],
 '109374': ['Grand Budapest Hotel, The (2014)'],
 '109376': ['Cuban Fury (2014)'],
 '109390': ['Black Coal, Thin Ice (Bai ri yan huo) (2014)'],
 '1094': ['Crying Game, The (1992)'],
 '109452': ['Omar (2013)'],
 '109463': ['7 Boxes (2012)'],
 '109483': ['That Awkward Moment (2014)'],
 '109487': ['Interstellar (2014)'],
 '1095': ['Glengarry Glen Ross (1992)'],
 '109569': ['3 Days to Kill (2014)'],
 '109578': ['Non-Stop (2014)'],
 '1096': ["Sophie's Choice (1982)"],
 '109607': ['In Fear (2013)'],
 '109633': ['Garden of Words, The (Koto no ha no niwa) (2013)'],
 '109673': ['300: Rise of an Empire (2014)'],
 '109682': ["Sumo Do, Sumo Don't (Shiko funjatta) (1992)"],
 '1097': ['E.T. the Extra-Terrestrial (1982)'],
 '109720': ['Contracted (2013)'],
 '109742': ['Cheap Thrills (2013)'],
 '109848': ['Under the Skin (2013)'],
 '109850': ['Need for Speed (2014)'],
 '109864': ['Veronica Mars (2014)'],
 '1099': ['Christmas Carol, A (1938)'],
 '11': ['American President, The (1995)'],
 '110': ['Braveheart (1995)'],
 '1100': ['Days of Thunder (1990)'],
 '110030': ['Bless Me, Ultima (2013)'],
 '110039': ['Space Pirate Captain Harlock (2013)'],
 '1101': ['Top Gun (1986)'],
 '110102': ['Captain America: The Winter Soldier (2014)'],
 '110110': ['Starred Up (2013)'],
 '110127': ['Noah (2014)'],
 '110169': ['Les Lyonnais (2011)'],
 '110173': ['Wolf (2013)'],
 '110216': ['BloodRayne: The Third Reich (2011)'],
 '1103': ['Rebel Without a Cause (1955)'],
 '110322': ['Dom Hemingway (2014)'],
 '110337': ['Moebius (2013)'],
 '1104': ['Streetcar Named Desire, A (1951)'],
 '110407': ['Machine, The (2013)'],
 '110453': ['Draft Day (2014)'],
 '110461': ['We Are the Best! (Vi är bäst!) (2013)'],
 '1105': ['Children of the Corn IV: The Gathering (1996)'],
 '110501': ['The Raid 2: Berandal (2014)'],
 '110553': ['The Amazing Spider-Man 2 (2014)'],
 '110557': ['Graceland (2012)'],
 '110586': ['Calvary (2014)'],
 '110591': ['Oculus (2013)'],
 '110611': ['Cold in July (2014)'],
 '110633': ['Arsène Lupin (1932)'],
 '110655': ['Rio 2 (2014)'],
 '110718': ['Fading Gigolo (2013)'],
 '110730': ['Transcendence (2014)'],
 '110771': ['Other Woman, The (2014)'],
 '110809': ['Vampire Academy (2014)'],
 '110826': ['Brick Mansions (2014)'],
 '110828': ["Devil's Knot (2013)"],
 '110882': ['Locke (2013)'],
 '111': ['Taxi Driver (1976)'],
 '1111': ["Microcosmos (Microcosmos: Le peuple de l'herbe) (1996)"],
 '111113': ['Neighbors (2014)'],
 '1112': ['Palookaville (1996)'],
 '111235': ["Jodorowsky's Dune (2013)"],
 '111249': ['Belle (2013)'],

In [ ]:
def similar_watch(v, n = 6):
     
    # extract most similar movies for the input vector
    ms = model.wv.similar_by_vector(v, topn= n+1)[1:]
     
    # extract name and similarity score of the similar movies
    new_ms = []
    for j in ms:
        pair = (watch_dict[j[0]][0], j[1])
        new_ms.append(pair)
         
    return new_ms

In [ ]:
print(watch_dict['4'])
similar_watch(model.wv['307'])

['Waiting to Exhale (1995)']

[('Three Colors: White (Trzy kolory: Bialy) (1994)', 0.9864673614501953),
 ('Three Colors: Red (Trois couleurs: Rouge) (1994)', 0.982518196105957),
 ('To Live (Huozhe) (1994)', 0.9699200987815857),
 ('Priest (1994)', 0.9658581018447876),
 ('Secret of Roan Inish, The (1994)', 0.9642032384872437),
 ('Shallow Grave (1994)', 0.9590436816215515)]