In [1]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import ipywidgets as widgets
from IPython.display import display,clear_output

# https://files.grouplens.org/datasets/movielens/ml-25m.zip
movies = pd.read_csv("movies.csv")

In [2]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [3]:
def clean_title(title):
    title = re.sub("[^a-zA-Z0-9 ]", "", title)
    return title

In [4]:
movies["clean_title"] = movies["title"].apply(clean_title)

In [5]:
movies

,movieId,title,genres,clean_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story 1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,Jumanji 1995
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men 1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Waiting to Exhale 1995
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II 1995
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,Black Butler Book of the Atlantic 2017
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,No Game No Life Zero 2017
9739,193585,Flint (2017),Drama,Flint 2017
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,Bungo Stray Dogs Dead Apple 2018
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,Andrew Dice Clay Dice Rules 1991

In [6]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))

tfidf = vectorizer.fit_transform(movies["clean_title"])

In [7]:
def search(title):
    title = clean_title(title)
    query_vec = vectorizer.transform([title])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    results = movies.iloc[indices].iloc[::-1]
    return results

In [8]:
search("The Hulk")

,movieId,title,genres,clean_title
4422,6534,Hulk (2003),Action|Adventure|Sci-Fi,Hulk 2003
8145,102058,Hulk Vs. (2009),Animation,Hulk Vs 2009
6770,60040,"Incredible Hulk, The (2008)",Action|Sci-Fi,Incredible Hulk The 2008
9058,142056,Iron Man & Hulk: Heroes United (2013),Action|Adventure|Animation,Iron Man Hulk Heroes United 2013
9513,171251,"Nobody Speak: Hulk Hogan, Gawker and Trials of...",Documentary,Nobody Speak Hulk Hogan Gawker and Trials of a...

In [9]:
ratings = pd.read_csv("ratings.csv")

In [10]:
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [11]:
ratings.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [12]:
movie_id = 1

In [13]:
similar_users = ratings[(ratings["movieId"] ==  movie_id) & (ratings["rating"] >= 4 )]["userId"].unique()

In [14]:
similar_users

array([  1,   5,   7,  17,  19,  31,  40,  43,  45,  46,  57,  63,  64,
        66,  71,  73,  78,  86,  91,  96,  98, 103, 107, 121, 124, 135,
       137, 141, 145, 151, 156, 159, 160, 161, 166, 169, 171, 177, 178,
       179, 182, 185, 186, 191, 201, 202, 206, 217, 220, 229, 234, 239,
       240, 247, 249, 252, 254, 263, 264, 269, 270, 273, 274, 275, 276,
       277, 280, 282, 288, 290, 291, 292, 304, 307, 328, 330, 332, 336,
       337, 339, 341, 347, 350, 353, 357, 359, 364, 367, 378, 380, 382,
       385, 389, 396, 399, 411, 414, 420, 422, 434, 436, 438, 443, 448,
       451, 453, 456, 460, 468, 469, 470, 471, 474, 476, 477, 483, 484,
       488, 492, 500, 504, 509, 514, 517, 524, 525, 533, 534, 550, 555,
       559, 561, 562, 570, 572, 573, 579, 584, 587, 590, 596, 597, 601,
       603, 605, 607, 610])

In [15]:
similar_user_recs = ratings[(ratings["userId"].isin(similar_users))&(ratings["rating"] >=4)]["movieId"]

In [16]:
similar_user_recs

0              1
1              3
2              6
3             47
4             50
           ...
100830    166528
100831    166534
100832    168248
100833    168250
100834    168252
Name: movieId, Length: 20964, dtype: int64

In [17]:
similar_user_recs = similar_user_recs.value_counts() / len(similar_users)

similar_user_recs = similar_user_recs[similar_user_recs > .1]

In [18]:
similar_user_recs

movieId
1       1.000000
318     0.585034
356     0.551020
260     0.530612
296     0.503401
          ...
5464    0.102041
1500    0.102041
4308    0.102041
2951    0.102041
661     0.102041
Name: count, Length: 315, dtype: float64

In [19]:
all_users = ratings[(ratings["movieId"].isin(similar_user_recs.index)) & (ratings["rating"] > 4)]

In [20]:
all_users_recs = all_users["movieId"].value_counts() / len(all_users["userId"].unique())

In [21]:
all_users_recs

movieId
318     0.346484
296     0.286449
356     0.265866
2571    0.257290
2959    0.222985
          ...
2291    0.013722
1370    0.013722
788     0.012007
2420    0.010292
440     0.008576
Name: count, Length: 315, dtype: float64

In [22]:
rec_percentages = pd.concat([similar_user_recs, all_users_recs],axis=1)
rec_percentages.columns = ["similar","all"]

In [23]:
rec_percentages

          similar       all
movieId
1        1.000000  0.111492
318      0.585034  0.346484
356      0.551020  0.265866
260      0.530612  0.219554
296      0.503401  0.286449
...           ...       ...
5464     0.102041  0.013722
1500     0.102041  0.025729
4308     0.102041  0.025729
2951     0.102041  0.025729
661      0.102041  0.013722

[315 rows x 2 columns]

In [24]:
rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]

In [25]:
rec_percentages = rec_percentages.sort_values("score",ascending=False)

In [26]:
rec_percentages

          similar       all      score
movieId
440      0.142857  0.008576  16.657143
2291     0.142857  0.013722  10.410714
2420     0.102041  0.010292   9.914966
21       0.149660  0.015437   9.694633
141      0.129252  0.013722   9.419218
...           ...       ...        ...
296      0.503401  0.286449   1.757383
4973     0.176871  0.101201   1.747723
2571     0.442177  0.257290   1.718594
318      0.585034  0.346484   1.688489
2959     0.374150  0.222985   1.677917

[315 rows x 3 columns]

In [27]:
rec_percentages.head(10).merge(movies,left_index=True, right_on="movieId")

,similar,all,score,movieId,title,genres,clean_title
383,0.142857,0.008576,16.657143,440,Dave (1993),Comedy|Romance,Dave 1993
1704,0.142857,0.013722,10.410714,2291,Edward Scissorhands (1990),Drama|Fantasy|Romance,Edward Scissorhands 1990
1820,0.102041,0.010292,9.914966,2420,"Karate Kid, The (1984)",Drama,Karate Kid The 1984
20,0.149660,0.015437,9.694633,21,Get Shorty (1995),Comedy|Crime|Thriller,Get Shorty 1995
116,0.129252,0.013722,9.419218,141,"Birdcage, The (1996)",Comedy,Birdcage The 1996
1232,0.156463,0.017153,9.121769,1641,"Full Monty, The (1997)",Comedy|Drama,Full Monty The 1997
0,1.000000,0.111492,8.969231,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story 1995
1986,0.122449,0.013722,8.923469,2640,Superman (1978),Action|Adventure|Sci-Fi,Superman 1978
622,0.102041,0.012007,8.498542,788,"Nutty Professor, The (1996)",Comedy|Fantasy|Romance|Sci-Fi,Nutty Professor The 1996
1053,0.115646,0.013722,8.427721,1370,Die Hard 2 (1990),Action|Adventure|Thriller,Die Hard 2 1990

In [28]:
def find_similar_movies(movie_id):
    similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] > 4)]["userId"].unique()
    similar_user_recs = ratings[(ratings["userId"].isin(similar_users)) & (ratings["rating"] > 4)]["movieId"]
    
    similar_user_recs = similar_user_recs.value_counts() / len(similar_users)
    similar_user_recs = similar_user_recs[similar_user_recs > .10]
    
    all_users = ratings[(ratings["movieId"].isin(similar_user_recs.index)) & (ratings["rating"] > 4)]
    all_user_recs = all_users["movieId"].value_counts() / len(all_users["userId"].unique())
    
    rec_percentages = pd.concat([similar_user_recs, all_user_recs], axis=1)
    rec_percentages.columns = ["similar", "all"]
    
    rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
    
    rec_percentages = rec_percentages.sort_values("score", ascending=False)
    return rec_percentages.head(10).merge(movies, left_index=True, right_on="movieId")[["score", "title", "genres"]]

In [29]:
display(find_similar_movies(1))

,score,title,genres
0,8.584615,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2355,5.202797,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy
7355,4.905495,Toy Story 3 (2010),Adventure|Animation|Children|Comedy|Fantasy|IMAX
436,4.544796,Mrs. Doubtfire (1993),Comedy|Drama
5374,3.219231,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
32,3.147692,Babe (1995),Children|Drama
2038,3.147692,Ghostbusters (a.k.a. Ghost Busters) (1984),Action|Comedy|Sci-Fi
506,2.985953,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
592,2.861538,"Rock, The (1996)",Action|Adventure|Thriller
5260,2.747077,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX